// <auto-generated />
using BapesTwitterBot.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BapesTwitterBot.Domain.Migrations
{
    [DbContext(typeof(BapesTwitterBotContext))]
    [Migration("20180210050856_AddedAccessToken")]
    partial class AddedAccessToken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BapesTwitterBot.Domain.Models.TwitterUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessToken");

                    b.Property<string>("AccessTokenSecret");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("TwitterUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
